/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public//models/Anciana System.glb -t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useNavigate } from 'react-router-dom'

type GLTFResult = GLTF & {
  nodes: {
    star_orbit_4: THREE.Mesh
    star: THREE.Mesh
    gas_giant_2: THREE.Mesh
    Circle006: THREE.Mesh
    Icosphere006: THREE.Mesh
    Icosphere007: THREE.Mesh
    star_orbit_3: THREE.Mesh
    star_orbit_2: THREE.Mesh
    star_orbit_1: THREE.Mesh
    planet_1: THREE.Mesh
    gas_giant_1: THREE.Mesh
    Circle001_1: THREE.Mesh
    Icosphere001_1: THREE.Mesh
    gas_giant_1_ring: THREE.Mesh
    planet_2: THREE.Mesh
    planet_3: THREE.Mesh
    star_orbit_5: THREE.Mesh
    comet_orbit: THREE.Mesh
    asteroid_belt: THREE.Mesh
    asteroid_belt2: THREE.Mesh
    planet_4: THREE.Mesh
    Circle_1: THREE.Mesh
    comet: THREE.Mesh
    comet_trail: THREE.Mesh
  }
  materials: {
    orbit: THREE.MeshStandardMaterial
    Star: THREE.MeshStandardMaterial
    ['gas Giant 1']: THREE.MeshStandardMaterial
    dwarf_planet: THREE.MeshStandardMaterial
    Planet2: THREE.MeshStandardMaterial
    ['gas Giant 2']: THREE.MeshStandardMaterial
    ring: THREE.MeshStandardMaterial
    Planet: THREE.MeshStandardMaterial
    Planet3: THREE.MeshStandardMaterial
    orbit_dashed: THREE.MeshStandardMaterial
    Asteroid: THREE.MeshStandardMaterial
    Comet: THREE.MeshStandardMaterial
    Comet_trail: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function AncianaSystem(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Anciana System.glb') as GLTFResult
  const navigate = useNavigate();
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.star_orbit_4.geometry} material={materials.orbit} rotation={[0.25, 0.2, -0.181]} scale={11.539} />
      <mesh onClick={() => navigate('/objects/1', { replace: true })} geometry={nodes.star.geometry} material={materials.Star} scale={1.402} > 
        <Html><div className='planet_name'>Sagitarious</div></Html>
      </mesh>
      <mesh onClick={() => navigate('/objects/6', { replace: true })} geometry={nodes.gas_giant_2.geometry} material={materials['gas Giant 1']} position={[-10.127, 2.915, -4.602]} scale={0.808}>
        <Html><div className='planet_name'>HIQ-220</div></Html>
        <mesh geometry={nodes.Circle006.geometry} material={materials.orbit} position={[-0.002, 0.07, -0.07]} rotation={[0.106, -0.175, 0.302]} scale={1.684}>
          <mesh geometry={nodes.Icosphere006.geometry} material={materials.dwarf_planet} position={[0.419, 0, 0.904]} scale={0.119} />
          <mesh geometry={nodes.Icosphere007.geometry} material={materials.dwarf_planet} position={[-0.44, 0, -0.883]} scale={0.068} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.star_orbit_3.geometry} material={materials.orbit} scale={8.632} />
      <mesh geometry={nodes.star_orbit_2.geometry} material={materials.orbit} scale={5.432} />
      <mesh geometry={nodes.star_orbit_1.geometry} material={materials.orbit} rotation={[0.12, 0.22, -0.175]} scale={3.619} />
      <mesh onClick={() => navigate('/objects/2', { replace: true })} geometry={nodes.planet_1.geometry} material={materials.Planet2} position={[-3.589, 0.724, 0.091]} scale={0.314} > 
        <Html><div className='planet_name'>HIO-204</div></Html>  
      </mesh>
      <mesh onClick={() => navigate('/objects/3', { replace: true })} geometry={nodes.gas_giant_1.geometry} material={materials['gas Giant 2']} position={[2.32, 0, -4.871]} rotation={[-0.167, 0.085, 0.434]} scale={0.784}>
        <Html><div className='planet_name'>HOK-542-R</div></Html>
          {/* <mesh geometry={nodes.Circle001_1.geometry} material={materials.orbit} position={[-0.004, 0.023, -0.03]} rotation={[0.106, -0.175, 0.302]} scale={1.961}>
            <mesh geometry={nodes.Icosphere001_1.geometry} material={materials.dwarf_planet} position={[0.419, 0, 0.904]} scale={0.119} />
          </mesh> */}
        <mesh geometry={nodes.gas_giant_1_ring.geometry} material={materials.ring} position={[-0.017, 0, -0.013]} scale={1.524} />
      </mesh>
      <mesh onClick={() => navigate('/objects/4', { replace: true })} geometry={nodes.planet_2.geometry} material={materials.Planet} position={[3.474, 0, 0.83]} scale={0.459} > 
        <Html><div className='planet_name'>HIQ-223</div></Html>
      </mesh>
      <mesh onClick={() => navigate('/objects/5', { replace: true })} geometry={nodes.planet_3.geometry} material={materials.Planet3} position={[-4.396, 0, -7.409]} scale={0.447} > 
        <Html><div className='planet_name'>HIQ-402</div></Html>
      </mesh>
      <mesh geometry={nodes.star_orbit_5.geometry} material={materials.orbit} rotation={[0.001, -0.315, 0.197]} scale={17.333} />
      <mesh geometry={nodes.comet_orbit.geometry} material={materials.orbit_dashed} position={[-8.28, 4.051, 0.141]} rotation={[0.18, 0.236, -0.598]} scale={[0.159, 0.2, 0.2]} />
      <mesh onClick={() => navigate('/objects/8', { replace: true })} geometry={nodes.asteroid_belt.geometry} material={materials.Asteroid} > 
        <Html><div className='planet_name'>AR-4-203-p</div></Html>
      </mesh>
      <mesh onClick={() => navigate('/objects/9', { replace: true })} geometry={nodes.asteroid_belt2.geometry} material={materials.Asteroid} > 
        <Html><div className='planet_name'>AR-4-204-p</div></Html>
      </mesh>
      <mesh onClick={() => navigate('/objects/7', { replace: true })} geometry={nodes.planet_4.geometry} material={materials.Planet2} position={[-4.28, 0.162, 16.664]} rotation={[0.034, -0.682, -0.451]} scale={0.628}>
        <Html><div className='planet_name'>HIQ-225</div></Html>
        {/* <mesh geometry={nodes.Circle_1.geometry} material={materials.ring} position={[-0.018, -0.022, 0.015]} scale={1.27} /> */}
      </mesh>
      <mesh onClick={() => navigate('/objects/10', { replace: true })} geometry={nodes.comet.geometry} material={materials.Comet} position={[-14.713, 8.33, -3.148]} scale={0.142} > 
        <Html><div className='planet_name'>OMA-2-504</div></Html>
      </mesh>
      <mesh geometry={nodes.comet_trail.geometry} material={materials.Comet_trail} position={[-14.861, 8.428, -3.069]} rotation={[0.438, 0.263, 0.923]} scale={0.142} />
    </group>
  )
}

useGLTF.preload('/models/Anciana System.glb')
