/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Anciana system_asteroids.glb -t 
*/

import * as THREE from 'three'
// import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    asteroid_belt: THREE.Mesh
    asteroid_belt2: THREE.Mesh
  }
  materials: {
    Asteroid: THREE.MeshStandardMaterial
  }
}

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Asteroids(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/SagaliStarSystem/models/Asteroids.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.asteroid_belt.geometry} material={materials.Asteroid} position={[6.558, -0.686, 3.572]} />
      <mesh geometry={nodes.asteroid_belt2.geometry} material={materials.Asteroid} position={[13.233, 0.989, 8.214]} />
    </group>
  )
}

useGLTF.preload('/SagaliStarSystem/models/Asteroids.glb')
