/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Coordinates.glb -t 
*/

import * as THREE from 'three'
// import React, { useRef } from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    asteroid_belt1_coord: THREE.Mesh
    asteroid_belt2_coord: THREE.Mesh
    gas_giant_1_coord: THREE.Mesh
    gas_giant_2_coord: THREE.Mesh
    planet_1_coord: THREE.Mesh
    planet_2_coord: THREE.Mesh
    planet_3_coord: THREE.Mesh
    planet_4_coord: THREE.Mesh
    star_coord: THREE.Mesh
    comet_coord: THREE.Mesh
  }
  materials: {}
}

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Coordinates(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/SagaliStarSystem/models/Coordinates.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.asteroid_belt1_coord.geometry} material={nodes.asteroid_belt1_coord.material} position={[6.558, -0.686, 3.572]} scale={0.033} >
        <Html><div className='planet_name'>AR-204-p</div></Html>
      </mesh>
      <mesh geometry={nodes.asteroid_belt2_coord.geometry} material={nodes.asteroid_belt2_coord.material} position={[13.233, 0.989, 8.214]} scale={0.033} >
        <Html><div className='planet_name'>AR-221-p</div></Html>
      </mesh>
      <mesh geometry={nodes.gas_giant_1_coord.geometry} material={nodes.gas_giant_1_coord.material} position={[2.32, 0, -4.871]} scale={0.033} >
        <Html><div className='planet_name'>HOK-542-R</div></Html>
      </mesh>
      <mesh geometry={nodes.gas_giant_2_coord.geometry} material={nodes.gas_giant_2_coord.material} position={[-10.127, 2.915, -4.602]} scale={0.033} >
        <Html><div className='planet_name'>HOK-535-R</div></Html>
      </mesh>
      <mesh geometry={nodes.planet_1_coord.geometry} material={nodes.planet_1_coord.material} position={[-3.589, 0.724, 0.091]} scale={0.033} >
        <Html><div className='planet_name'>HIQ-225</div></Html>
      </mesh>
      <mesh geometry={nodes.planet_2_coord.geometry} material={nodes.planet_2_coord.material} position={[3.474, 0, 0.83]} scale={0.033} >
        <Html><div className='planet_name'>HIQ-402</div></Html>
      </mesh>
      <mesh geometry={nodes.planet_3_coord.geometry} material={nodes.planet_3_coord.material} position={[-4.396, 0, -7.409]} scale={0.033} >
        <Html><div className='planet_name'>HIQ-223</div></Html>
      </mesh>
      <mesh geometry={nodes.planet_4_coord.geometry} material={nodes.planet_4_coord.material} position={[-4.28, 0.162, 16.664]} scale={0.033} >
        <Html><div className='planet_name'>HIO-204</div></Html>  
      </mesh>
      <mesh geometry={nodes.star_coord.geometry} material={nodes.star_coord.material} scale={0.033} >
        <Html><div className='planet_name'>Sagitarious</div></Html>
      </mesh>
      <mesh geometry={nodes.comet_coord.geometry} material={nodes.comet_coord.material} position={[-14.713, 8.33, -3.148]} scale={0.033} >
        <Html><div className='planet_name'>OMA-2-504</div></Html>
      </mesh>
    </group>
  )
}

useGLTF.preload('/SagaliStarSystem/models/Coordinates.glb')
