/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/gas_giant_1.glb -t 
*/

import * as THREE from 'three'
// import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    gas_giant_1: THREE.Mesh
    gas_giant_1_ring: THREE.Mesh
  }
  materials: {
    ['gas Giant 2.001']: THREE.MeshStandardMaterial
    ['ring.002']: THREE.MeshStandardMaterial
  }
}

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Gas_giant_1(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/SagaliStarSystem/models/gas_giant_1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.gas_giant_1.geometry} material={materials['gas Giant 2.001']} rotation={[-0.167, 0.085, 0.434]} scale={0.784}>
        <mesh geometry={nodes.gas_giant_1_ring.geometry} material={materials['ring.002']} position={[-0.017, 0, -0.013]} scale={1.524} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/SagaliStarSystem/models/gas_giant_1.glb')
