/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/gas_giant_2.glb -t 
*/

import * as THREE from 'three'
// import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    gas_giant_2: THREE.Mesh
  }
  materials: {
    ['gas Giant 1.001']: THREE.MeshStandardMaterial
  }
}

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Gas_giant_2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/SagaliStarSystem/models/gas_giant_2.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.gas_giant_2.geometry} material={materials['gas Giant 1.001']} scale={0.808} />
    </group>
  )
}

useGLTF.preload('/SagaliStarSystem/models/gas_giant_2.glb')
