/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/planet_1.glb -t 
*/

import * as THREE from 'three'
// import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    planet_1: THREE.Mesh
  }
  materials: {
    ['Planet2.001']: THREE.MeshStandardMaterial
  }
}

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Planet_1(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/SagaliStarSystem/models/planet_1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.planet_1.geometry} material={materials['Planet2.001']} scale={0.314} />
    </group>
  )
}

useGLTF.preload('/SagaliStarSystem/models/planet_1.glb')
