/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/planet_4.glb -t 
*/

import * as THREE from 'three'
// import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    planet_4: THREE.Mesh
    planet_4_ring: THREE.Mesh
  }
  materials: {
    ['Planet3.001']: THREE.MeshStandardMaterial
    ['ring.001']: THREE.MeshStandardMaterial
  }
}

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Planet_4(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/SagaliStarSystem/models/planet_4.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.planet_4.geometry} material={materials['Planet3.001']} rotation={[0.034, -0.682, -0.451]} scale={0.628}>
        <mesh geometry={nodes.planet_4_ring.geometry} material={materials['ring.001']} position={[-0.018, -0.022, 0.015]} scale={1.27} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/SagaliStarSystem/models/planet_4.glb')
