/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Star.glb -t 
*/

import * as THREE from 'three'
// import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    star: THREE.Mesh
  }
  materials: {
    ['Star.001']: THREE.MeshStandardMaterial
  }
}

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Star(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/SagaliStarSystem/models/Star.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.star.geometry} material={materials['Star.001']} scale={1.402} />
    </group>
  )
}

useGLTF.preload('/SagaliStarSystem/models/Star.glb')
